# Modify this file and then copy to config.yml
image:
  web_path: /static/uploads/
  path: ./static/uploads/
  thumb_path: ./static/uploads/thumbs/
  thumb_web_path: /static/uploads/thumbs/
  max_size:
    width: 1600
    height: 1200

generate:
  public_web_path: /published/
  limited_web_path: /private/

theme:
  theme_dir: ./static/themes/simple
  web_path: /static/themes/simple/

database:
  path: ./kodiak.sql

app:
  static_web_path: /static/
  web_path: /
  host: https://goodrobot.net
  twitter_username: @goodrobot

# Generate a secret key:
# >>> import os
# >>> os.urandom(24)
# copy output below
secret_key: fluffy_secret
